parameters:
  - name: "feet_air_time.weight"
    weights: [2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5]
  - name: "track_ang_vel_z_exp.weight"
    weights: [3.0, 2.7, 2.4, 2.1, 1.8, 1.5, 1.2, 0.9]
  - name: "track_lin_vel_xy_exp.weight"
    weights: [1.5, 1.8, 2.1, 2.4, 2.7, 3.0, 3.3, 3.6]
